### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Pid 16700 has exceeded the number of permissible registered listeners. Ignoring request to add.

### ISSUE THREAD

**Issue by mwshubham** [Conviva/conviva-android-coresdk#4]
Hi Conviva Team, 

We are facing the following problem

Stack Trace:

```
Fatal Exception: java.lang.IllegalStateException: Pid 16700 has exceeded the number of permissible registered listeners. Ignoring request to add.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2397)
       at android.os.Parcel.createException(Parcel.java:2373)
       at android.os.Parcel.readException(Parcel.java:2356)
       at android.os.Parcel.readException(Parcel.java:2298)
       at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenForSubscriber(ITelephonyRegistry.java:1105)
       at android.telephony.TelephonyRegistryManager.listenForSubscriber(TelephonyRegistryManager.java:255)
       at android.telephony.TelephonyManager.listen(TelephonyManager.java:5775)
       at com.conviva.platforms.android.AndroidNetworkUtils$1.run(AndroidNetworkUtils.java:189)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:254)
       at android.app.ActivityThread.main(ActivityThread.java:8199)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```
![image](https://user-images.githubusercontent.com/29930308/124883895-6a634300-dfef-11eb-9193-f40fbf88de8f.png)

We are using following dependencies

```
    api 'com.conviva.sdk:conviva-core-sdk:4.0.11.150'
    api 'com.conviva.sdk:conviva-exoplayer-sdk:4.0.6.52'
```

**Comment by mwshubham** [comment]
This is fixed in 
 api 'com.conviva.sdk:conviva-core-sdk:4.0.16.187'
    api 'com.conviva.sdk:conviva-exoplayer-sdk:4.0.7.61'
    
    Thanks
