### ISSUE TITLE
NullPointer in onAppForeground and onAppBackground

### ISSUE THREAD

**Issue by DJansse** [Conviva/conviva-android-coresdk#7]
Hi Conviva, 

When the app is pushed to the foreground / background after the Conviva client has been released, a NPE will occur due to the ProcessObserver:

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.conviva.sdk.ConvivaAnalytics$2.onAppForeground(ConvivaAnalytics.java:79)
       at com.conviva.api.ProcessObserver.onActivityStarted(ProcessObserver.java:53)
       at android.app.Application.dispatchActivityStarted(Application.java:241)
       at android.app.Activity.onStart(Activity.java:1301)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:496)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at com.android.tv.MainActivity.onStart(MainActivity.java:1127)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
       at android.app.Activity.performStart(Activity.java:7194)
       at android.app.Activity.performRestart(Activity.java:7311)
       at android.app.ActivityThread.handleSleeping(ActivityThread.java:4374)
       at android.app.ActivityThread.access$2400(ActivityThread.java:208)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:6769)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

The callback methods don't check the analyticsList object for null:
`ProcessObserver.getInstance().setCallback(new Callback() {
            public void onAppForeground() {
                Iterator var1 = ConvivaAnalytics.analyticsList.iterator();

                while(var1.hasNext()) {
                    ConvivaExperienceAnalytics analytics = (ConvivaExperienceAnalytics)var1.next();
                    analytics.reportPlaybackEvent(Events.FOREGROUND.getValue());
                }

            }

            public void onAppBackground() {
                Iterator var1 = ConvivaAnalytics.analyticsList.iterator();

                while(var1.hasNext()) {
                    ConvivaExperienceAnalytics analytics = (ConvivaExperienceAnalytics)var1.next();
                    analytics.reportPlaybackEvent(Events.BACKGROUND.getValue());
                }

            }
        });`

Currently the Firebase crashes indicate this issue in onAppForeground and on onAppBackground 46 time in 2 days.
The used Conviva library is "4.0.30"

Kind regards

**Comment by SarathRamachandra** [comment]
@DJansse : Thanks for bringing up this issue to us. We will look into this issue and will provide you feedback sooner.

**Comment by SarathRamachandra** [comment]
Issue is resolved in the version [v4.0.32](https://github.com/Conviva/conviva-android-coresdk/releases/tag/4.0.32)

4.0.32 (19/JUN/2023)
Fixes the crash issue when the app is backgrounded or foregrounded after release is called.
