### ISSUE TITLE
ConcurrentModificationException in onAppBackground

### ISSUE THREAD

**Issue by DJansse** [Conviva/conviva-android-coresdk#8]
Hi Conviva,

A concurrentModificationException can occur in onAppBackground while iterating the analyticsList:

`Caused by java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.conviva.sdk.ConvivaAnalytics$2.onAppBackground(ConvivaAnalytics.java:86)
       at com.conviva.api.ProcessObserver.onActivityStopped(ProcessObserver.java:75)
       at android.app.Application.dispatchActivityStopped(Application.java:268)
       at android.app.Activity.onStop(Activity.java:1942)
       at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:520)
       at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:252)
       at com.android.tv.MainActivity.onStop(MainActivity.java:1564)
       at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1432)
       at android.app.Activity.performStop(Activity.java:7428)
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4221)
       at android.app.ActivityThread.handleSleeping(ActivityThread.java:4358)
       at android.app.ActivityThread.access$2400(ActivityThread.java:208)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:6769)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

This is seen with Conviva version "4.0.30" with 19 crashes in the last 4 days (Firebase). I don't know the exact scenario.

Kind regards

**Comment by SarathRamachandra** [comment]
@DJansse thanks for bringing it up to us. We will have a look into this issue and will provide you the feedback soon.

**Comment by SarathRamachandra** [comment]
Issue is resolved in the version [v4.0.32](https://github.com/Conviva/conviva-android-coresdk/releases/tag/4.0.32)

4.0.32 (19/JUN/2023)
Fixes the crash issue when the app is backgrounded or foregrounded after release is called.
